/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'oklch(var(--border) / <alpha-value>)',
        input: 'oklch(var(--input) / <alpha-value>)',
        ring: 'oklch(var(--ring) / <alpha-value>)',
        background: '#f9f9f9',
        foreground: '#1a1c1c',
        primary: {
          DEFAULT: '#000000',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: '#5e5e5e',
          foreground: '#ffffff',
        },
        destructive: {
          DEFAULT: '#ba1a1a',
          foreground: '#ffffff',
        },
        muted: {
          DEFAULT: '#e2e2e2',
          foreground: '#4c4546',
        },
        accent: {
          DEFAULT: '#e3e2e2',
          foreground: '#1a1c1c',
        },
        popover: {
          DEFAULT: '#ffffff',
          foreground: '#1a1c1c',
        },
        card: {
          DEFAULT: '#ffffff',
          foreground: '#1a1c1c',
        },
        sidebar: {
          DEFAULT: '#f9f9f9',
          foreground: '#1a1c1c',
          primary: '#000000',
          'primary-foreground': '#ffffff',
          accent: '#e2e2e2',
          'accent-foreground': '#1a1c1c',
          border: '#000000',
          ring: '#000000',
        },
        'inverse-on-surface': '#f0f1f1',
        'surface-container': '#eeeeee',
        'outline-variant': '#cfc4c5',
        'surface-container-highest': '#e2e2e2',
        'inverse-primary': '#c6c6c6',
        'surface-bright': '#f9f9f9',
        'on-surface': '#1a1c1c',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#1a1c1c',
        'secondary-container': '#e3e2e2',
        'inverse-surface': '#2f3131',
        'surface': '#f9f9f9',
        'secondary-fixed-dim': '#c7c6c6',
        'on-tertiary-container': '#838484',
        'on-surface-variant': '#4c4546',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#c6c6c6',
        'primary-container': '#1b1b1b',
        'secondary-fixed': '#e3e2e2',
        'on-tertiary-fixed-variant': '#454747',
        'outline': '#7e7576',
        'on-secondary-container': '#646464',
        'on-primary-fixed': '#1b1b1b',
        'on-error': '#ffffff',
        'on-primary-container': '#848484',
        'tertiary-fixed-dim': '#c6c6c6',
        'primary-fixed': '#e2e2e2',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#e2e2e2',
        'tertiary': '#000000',
        'on-secondary-fixed-variant': '#464747',
        'tertiary-container': '#1a1c1c',
        'surface-container-high': '#e8e8e8',
        'surface-dim': '#dadada',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#474747',
        'on-secondary-fixed': '#1b1c1c',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#5e5e5e',
        'surface-container-low': '#f3f3f4',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1a1c1c',
      },
      borderRadius: {
        lg: '0px',
        md: '0px',
        sm: '0px',
        DEFAULT: '0px',
      },
      spacing: {
        gutter: '24px',
        'element-gap': '16px',
        'section-gap': '64px',
        unit: '8px',
        'container-padding': '32px',
      },
      fontFamily: {
        'headline-xl': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'stats-mono': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'stats-mono': ['18px', { lineHeight: '1', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
